### ISSUE TITLE
Trouble using the app.

### ISSUE THREAD

**Issue by nullptr448** [blacksmithop/imgen#9]
Everytime i make a request to a endpont that requires the `avatar1` header i get the 400 page.

GET https://imgen.herokuapp.com/aborted
> Headers
`avatar1: https://cdn.discordapp.com/avatars/711390470718226522/11ea62037641390c6954216f4905b325.png?size=1024`

Returns 400 error page.

**Comment by blacksmithop** [comment]
Thanks for checking out the repo!
The docs under the endpoint is referring to the use of url parameters, for using headers please refer the example on top.
In order to pass an avatar to the `aborted` endpoint you'd be making a request to `/abandon` with the following header

```
{'avatars': 'link1,link2'}
```
Where the links are comma separated values enclosed in quotes

A practical example of this
![image](https://user-images.githubusercontent.com/60320192/131204857-696b4979-5cc8-405c-9548-0b99742f22f1.png)

 Edit: An example of using url parameters to achieve the same
 
 `https://imgen.herokuapp.com/aborted?avatars=https://imgen.herokuapp.com/assets/ambu.png`

**Comment by blacksmithop** [comment]
I have moved all the recent changes to `master`, please clone the repo again or make sure to fetch that branch before trying again. Both url params as well as headers are supported in `master` branch. `dev` branch is not fully operational
